### ISSUE TITLE
what are the keys to train in another env successfully?

### ISSUE THREAD

**Issue by GELIELEO** [JohannesAck/MATD3implementation#1]
I want to train this agent in env [multi_speaker_listener](https://github.com/shariqiqbal2810/MAAC/blob/master/envs/mpe_scenarios/multi_speaker_listener.py) which use MPE as well, but I fall, the agent cannot obtain stable reward, so I want to ask what are the keys to train successfully in this new env?

Thank you!

**Comment by JohannesAck** [comment]
Sure, thanks for asking. The reason that in this environment MADDPG and MATD3 fail is explained by the authors of multi_speaker_listener, Shariq Iqbal and Fei Sha, in their paper here https://arxiv.org/pdf/1810.02912.pdf.

It mainly comes down to the environment involving a large number of agents, which leads to a large observation space for the centralized critic.

I haven't tested this, but I would assume that in general for environments with few agents (maybe 2-6 or so) MATD3 should work better, and that for environments with more their approach (MAAC) works better, due to the attention mechanism.
