### ISSUE TITLE
reproduce problem

### ISSUE THREAD

**Issue by Michael-Fuu** [JohannesAck/MATD3implementation#2]
Hi,
    When I try to reproduce your result of Figure1(about Q function bias), I get a really different result :![Figure_1](https://user-images.githubusercontent.com/55577878/121801584-9eef1380-cc6a-11eb-95ba-7f96828a1c8c.png)
It seems that both methods have overestimation.
    here is for reproduce:`python train.py --exp-name '6_13_1' --scenario simple_spread --good-policy matd3 --save-dir /home/***/MATD3implementation/matd3/model/6_13_1/policy/ --num-episodes 20000 --real-q-log`
    Any advice or guidance?Thanks

**Comment by JohannesAck** [comment]
Hi,
Thank you for your interest in the paper :)
I'm a bit busy right now so I don't have the time to rerun the experiments immediately, but I think I know what the issue might be:

In the experiment in which we compare the true and estimated q-values, we set the number of steps per episode to 200 during the training and then evaluate the q value over partial rollouts with 100 steps.
However, because the default value is 25, it trained for only 25 steps per episode and evaluated on rollouts of 100 steps in your experiment. As the reward is always negative, an episode with 25 steps will have a higher reward than one with 100 steps, leading to the figure you shared.

At least I think that's what's going on, it's been three years since I ran these experiments :sweat_smile:

Could you try running it with `--max-episode-len 200` and tell me if it fixed the issue?

**Comment by Michael-Fuu** [comment]
thanks for your patient reply! I tried your method and it really solved my problem. Anyway, the best of luck in your study!

**Comment by JohannesAck** [comment]
Great, I'm glad to hear it! Best of luck with what you're doing as well!
